language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
services:
- postgresql

before_install:
  - psql -c "\du" -U postgres | cat
  - psql -l | cat
  - psql -c "create database $USER;" -U postgres | cat
install:
  - cd ${TRAVIS_BUILD_DIR}
  - pip install --upgrade pip
  - pip install .[test]
  - pip freeze
script:
  - cd ${TRAVIS_BUILD_DIR}
  - tox
